---
name: Start Devbox

'on':
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd  # v6.3.0
        with:
          aws-region: ${{ vars.DEVBOX_AWS_REGION }}
          role-to-assume: ${{ vars.DEVBOX_AWS_ROLE_ARN }}
      - run: |
          aws ec2 start-instances --instance-ids ${{ vars.DEVBOX_INSTANCE_ID }} > /dev/null
          aws ec2 wait instance-running --instance-ids ${{ vars.DEVBOX_INSTANCE_ID }}
    timeout-minutes: 2
