---
name: Stop Devbox

'on':
  schedule:
    - cron: 0 4 * * *
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c  # v6.2.3
        with:
          aws-region: ${{ vars.DEVBOX_AWS_REGION }}
          role-to-assume: ${{ vars.DEVBOX_AWS_ROLE_ARN }}
      - run: |
          aws ec2 stop-instances --instance-ids ${{ vars.DEVBOX_INSTANCE_ID }} > /dev/null
          aws ec2 wait instance-stopped --instance-ids ${{ vars.DEVBOX_INSTANCE_ID }}
    timeout-minutes: 2
